export const SOCKET_EVENTS = {
  MESSAGE_SEND: 'message:send',
  MESSAGE_READ: 'message:read',
  CONVERSATION_READ: 'conversation:read',
  MESSAGE_REACT: 'message:react',
  TYPING_START: 'message:typing:start',
  TYPING_STOP: 'message:typing:stop',
  PRESENCE_UPDATE: 'presence:update',
  CHANNEL_JOIN: 'channel:join',
  CHANNEL_LEAVE: 'channel:leave',
  MESSAGE_NEW: 'message:new',
  MESSAGE_UPDATED: 'message:updated',
  MESSAGE_DELETED: 'message:deleted',
  REACTION_ADDED: 'message:reaction:added',
  REACTION_REMOVED: 'message:reaction:removed',
  READ_RECEIPT: 'message:read_receipt',
  TYPING_UPDATE: 'typing:update',
  PRESENCE_BROADCAST: 'presence:update',
  NOTIFICATION_NEW: 'notification:new',
  ANNOUNCEMENT_EMERGENCY: 'announcement:emergency',
  ERROR: 'error:socket',
} as const;
